### ISSUE TITLE
Project Name?

### ISSUE THREAD

**Issue by ANDREYDEN** [kgallego/4x4project#2]
Any ideas for the project name?

**Comment by kgallego** [comment]
Some ideas we came up with (though not that serious) while at shopify:

-safe space
-orbit

** some members thought adding the word "happy" or some other simple/fun word to the name would make it sound like something that's targeted for kids

-happy place
-happy galaxy
-happy planet

** the idea of incorporating animals in the project was also brought up

-space sheep

**Comment by ANDREYDEN** [comment]
Orbit Organizer
Astral Planner

**Comment by ANDREYDEN** [comment]
**Astrallife**
